---
- hosts: "{{servers}}"
  remote_user: "{{ansible_user}}"
  gather_facts: false
  tasks:
  - name: print debug msg for paramaters
    debug:
      msg:
        - "servers is: {{servers}}"
        - "ansible_user is: {{ansible_user}}"
        - "docker_host is: {{docker_host}}"
        - "repo is: {{repo}}"
        - "tag is: {{tag}}"

  - name: docker_pull
    shell: docker pull {{docker_host}}{{repo}}:{{tag}}
