---
- hosts: "{{servers}}"
  remote_user: "{{ansible_user}}"

  tasks:
  - name: print debug msg for paramaters
    debug:
      msg:
        - "servers is: {{servers}}"
        - "remote_user is: {{remote_user}}"
        - "docker_host is: {{docker_host}}"
        - "repo is: {{tag}}"
        - "tag is: {{tag}}"

  - name: docker_pull
    shell: docker pull {{docker_host}}{{repo}}:{{tag}}
