---
- hosts: "{{servers}}"
  remote_user: gateman
  vars:
    container_name: docker_mysql

  tasks:
    - name: use another common playbook to stop container
      import_playbook: ../common/common_docker_stop.yml
      vars:
        servers: {{servers}}
        ansible_user: "gateman"
        container_name: {{container_name}}