---
- hosts: "{{servers}}"
  remote_user: "{{remote_user}}"



- name: use another common playbook to stop container, could not be used in under setion tasks
  import_playbook: ../common/common_docker_stop.yml
  vars:
    servers: "{{servers}}"
    ansible_user: "{{remote_user}}"
    container_name: "{{container_name}}"
