---
- hosts: "{{servers}}"
  remote_user: "{{remote_user}}"

 - name: use another common playbook to stop container, could not be used in under setion tasks
   import_playbook: ../common/common_docker_pull.yml
   vars:
     servers: "{{servers}}"
     ansible_user: "{{remote_user}}"
     docker_host: "{{docker_host}}"
     repo: "{{repo}}"
     tag: "{{tag}}"


