---
- hosts: "{{servers}}"
  remote_user: root
  vars_files: ./user_list.yml
  tasks:
    - name: create user
      user:
        name: "{{ item.user }}"
        password: "{{ 'item.pass'|password_hash('sha512') }}"
        state: present
      loop: "{{ userlist }}"