---
- hosts: web_servers
  remote_user: gateman

  tasks:
  - name: dockerpull
    shell: docker pull registry.cn-hangzhou.aliyuncs.com/hsbc_jason/{{repo}}:{{tag}}
    register: docker_ps_rst # if no record returned by grep , the variable boolean value will be failed
    ignore_errors: True

  - name: print the docker ps result
    debug: var=docker_ps_rst verbosity=0 # log level , 0 = debug



