---
- hosts: web_servers
  remote_user: gateman

  tasks:
  - name: docker check is there a container running
    shell: docker ps -f "name={{container_name}}" | grep {{container_name}}
    register: docker_ps_rst # if no record returned by grep , the variable boolean value will be failed
    ignore_errors: True

  - name: print the docker ps result
    debug: var=docker_ps_rst verbosity=0 # log level , 0 = debug

 - name: print ps command is succeeded or not
    ansible.builtin.debug:
      msg:
        - The container {{container_name}} is existed in host {{ inventory_hostname }}, continue process..
    when: docker_ps_rst is success

  - name: docker stop it {{container_name}}
    shell: docker stop {{container_name}}
    when: docker_ps_rst is success